version: '3'

services:

  # Host===================================================================
  public_nginx:
    image: nginx:1.12
    container_name: public_nginx
    ports:
      - 8000:80
    volumes:
      - ./app/:/var/www/html/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx/

  # App===================================================================
  public_app:
    container_name: public_app
    build: docker/app
    volumes:
      - ./app/:/var/www/html/
      - ./docker/app/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini

  # NPM===================================================================
  public_node:
    image: node:lts
    container_name: public_node
    volumes:
      - ./app/:/var/www/html/
    #      - node:/var/www/html/node_modules ここもwindows特有のエラー対策
    working_dir: /var/www/html/
    entrypoint: [ "npm" ]
    command: [ "--help" ]

networks:
  default:
    name: car_catalog_network
    external: true

# windows環境で発生するnpm周りのエラー対策
#
#  node:
#    driver: local